name: build

on:
  push:
    paths:
    - .github/workflows/build.yml

env:
  IMAGE: ghcr.io/emgag/php
  REPO_OWNER: emgag-service

jobs:
  revs:
    runs-on: ubuntu-latest
    outputs:
      php:
        - upstream: "7.2.33"
          rev: ""
        - upstream: "7.3.21"
          rev: ""
        - upstream: "7.49.9"
          rev: ""
    steps:
      - name: noop
        run: echo "noop"

  base:
    strategy:
      matrix:
        php: ${{ needs.revs.outputs.php }}
        flavour:
          - cli
          - fpm
        source:
          - dir: base
            suffix: ""
          - dir: build
            suffix: "-build"

    runs-on: ubuntu-latest
    needs: [revs]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to github docker registry
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.CR_PAT }}

      - name: Build ${{ matrix.source }} image (${{ matrix.php.upstream}}{{ matrix.php.rev }}-${{ matrix.flavour }}${{ matrix.source.suffix }})
        run: >
          docker build --no-cache --pull \
          --build-arg VERSION=${{ matrix.php.upstream }} \
          --build-arg FLAVOUR=${{ matrix.flavour }} \
          -t ${{ env.IMAGE }}:${{ matrix.php.upstream }}${{ matrix.php.rev }}-${{ matrix.flavour }}${{ matrix.source.suffix }} \
          ${{ matrix.source.dir }}

      - name: Push ${{ matrix.source }} image (${{ matrix.php.upstream}}{{ matrix.php.rev }}-${{ matrix.flavour }}${{ matrix.source.suffix }})
        run: docker push ${{ env.IMAGE }}:${{ matrix.php.upstream }}${{ matrix.php.rev }}-${{ matrix.flavour }}${{ matrix.source.suffix }}

  cron:
    strategy:
      matrix:
        php: ${{ needs.revs.outputs.php }}

    runs-on: ubuntu-latest
    needs: [revs, base]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to github docker registry
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.CR_PAT }}

      - name: Build cron image (${{ matrix.php.upstream}}{{ matrix.php.rev }}-cron)
        run: >
          docker build --no-cache --pull \
          --build-arg VERSION=${{ matrix.php.upstream }} \
          --build-arg FLAVOUR=cli \
          -t ${{ env.IMAGE }}:${{ matrix.php.upstream }}${{ matrix.php.rev }}-cron \
          base

      - name: Push cron image (${{ matrix.php.upstream}}{{ matrix.php.rev }}-cron)
        run: docker push ${{ env.IMAGE }}:${{ matrix.php.upstream }}${{ matrix.php.rev }}-cron
